In [1]:
# unit test for adjacency matrix transform

import torch
import numpy as np
import scipy.sparse as sp

i=torch.LongTensor([[0,1,1],[2,0,2]])
j=i.t()

adj = sp.coo_matrix((np.ones(i.shape[0]), (i[:, 0], i[:, 1])),  # 构建边的邻接矩阵
                        shape=(5,5),
                        dtype=np.float32)
print(adj.A)
print('~~~~~~~~~~~')
print(adj.T > adj)
print('~~~~~~~~~~~')
print(adj.multiply(adj.T > adj))
print('~~~~~~~~~~~')
print(adj.T.multiply(adj.T > adj))
print('~~~~~~~~~~~')
adj = adj + adj.T.multiply(adj.T > adj) - adj.multiply(adj.T > adj)
print(adj.A)

[[0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
~~~~~~~~~~~
  (0, 2)	True
  (1, 0)	True
~~~~~~~~~~~

~~~~~~~~~~~
  (0, 2)	1.0
  (1, 0)	1.0
~~~~~~~~~~~
[[0. 1. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


/home/u1812652/.local/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
# https://blog.csdn.net/ysh1026/article/details/109559981

a = np.arange(12).reshape(3,4)
print('a:', a)
print('np.where(a > 5):', np.where(a > 5))
print('a[np.where(a > 5)]:', a[np.where(a > 5)])
print('np.where(a > 5)[0]:', np.where(a > 5)[0])
print('np.where(a > 5)[1]:', np.where(a > 5)[1])
print(a[np.where(a > 5)[0], np.where(a > 5)[1]])

a: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
np.where(a > 5): (array([1, 1, 2, 2, 2, 2]), array([2, 3, 0, 1, 2, 3]))
a[np.where(a > 5)]: [ 6  7  8  9 10 11]
np.where(a > 5)[0]: [1 1 2 2 2 2]
np.where(a > 5)[1]: [2 3 0 1 2 3]
[ 6  7  8  9 10 11]


In [3]:
import os

def encode_onehot(labels):
    classes = set(labels)#集合没有重复值，看看有多少个类型
    classes_dict = {c: np.identity(len(classes))[i, :] for i, c in
                    enumerate(classes)}#把classes变成字典
    #np.identity(len(classes))[i, :]，变成对角矩阵，并切割成i行
    #for i, c in enumerate(classes),i是索引,c是元素
    labels_onehot = np.array(list(map(classes_dict.get, labels)),
                             dtype=np.int32)
    return labels_onehot


path=os.path.join(os.getcwd(),'pygcn','data','cora')
dataset="cora"
idx_features_labels = np.genfromtxt("{}/{}.content".format(path, dataset),
                                        dtype=np.dtype(str))
labels = encode_onehot(idx_features_labels[:, -1])  # one-hot label

FileNotFoundError: /home/u1812652/Documents/code/pygcn/pygcn/pygcn/data/cora/cora.content not found.